'$schema' = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = false
palette = 'holow_light'

[palettes.holow_light]
fg0 = '#2e3440'
fg1 = '#3b4252'
blue = '#5e81ac'
green = '#5e8f63'
yellow = '#b26a33'
red = '#bf616a'

[username]
show_always = true
style_user = 'fg:fg0'
style_root = 'fg:red bold'
format = '[$user]($style) '

[hostname]
ssh_only = false
style = 'fg:fg1'
format = '[@$hostname]($style) '

[directory]
style = 'fg:blue bold'
format = '[$path]($style) '
truncation_length = 3
truncate_to_repo = false

[git_branch]
style = 'fg:green'
format = '[$branch]($style) '

[git_status]
style = 'fg:yellow'
format = '[$all_status$ahead_behind]($style) '

[cmd_duration]
min_time = 1000
style = 'fg:yellow'
format = '[$duration]($style) '

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
